INSERT INTO `cursos` (`nombre`) VALUES ('PRIMERO');
INSERT INTO `cursos` (`nombre`) VALUES ('SEGUNDO');
INSERT INTO `cursos` (`nombre`) VALUES ('TERCERO');
INSERT INTO `cursos` (`nombre`) VALUES ('CUARTO');
INSERT INTO `cursos` (`nombre`) VALUES ('QUINTO');
INSERT INTO `cursos` (`nombre`) VALUES ('SEXTO');

 
INSERT INTO `universidades` (`nombre`) VALUES ('Universidad de Sevilla');


INSERT INTO `facultades` (`nombre`, `universidad_id`) VALUES ('Escuela Técnica Superior de Ingeniería Informática', '1');
INSERT INTO `facultades` (`nombre`, `universidad_id`) VALUES ('Escuela Técnica Superior de Arquitectura', '1');
INSERT INTO `facultades` (`nombre`, `universidad_id`) VALUES ('Escuela Técnica Superior de Edificación', '1');
INSERT INTO `facultades` (`nombre`, `universidad_id`) VALUES ('Facultad de Física', '1');
INSERT INTO `facultades` (`nombre`, `universidad_id`) VALUES ('Facultad de Matemáticas', '1');
INSERT INTO `facultades` (`nombre`, `universidad_id`) VALUES ('Facultad de Química', '1');
INSERT INTO `facultades` (`nombre`, `universidad_id`) VALUES ('Facultad de Farmacia', '1');
INSERT INTO `facultades` (`nombre`, `universidad_id`) VALUES ('Facultad de Biología', '1');


INSERT INTO `grados` (`nombre`, `facultad_id`, `numerocursos`) VALUES ('Grado en Ingeniería Informática-Ingeniería del Software', '1', '4');
INSERT INTO `grados` (`nombre`, `facultad_id`, `numerocursos`) VALUES ('Grado en Ingeniería Informática-Ingeniería de Computadores', '1', '4');
INSERT INTO `grados` (`nombre`, `facultad_id`, `numerocursos`) VALUES ('Grado en Ingeniería Informática-Tecnologías Informáticas', '1', '4');
INSERT INTO `grados` (`nombre`, `facultad_id`, `numerocursos`) VALUES ('Grado en Ingeniería de la Salud', '1', '4');


INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Administración de Empresas', '1', '2050006', '6', '0', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Administración de Empresas', '1', '2040006', '6', '0', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Administración de Empresas', '1', '2060002', '6', '0', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Álgebra Lineal', '1', '2260001', '6', '0', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Álgebra Lineal y Numérica', '1', '2050007', '6', '0', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Álgebra Lineal y Numérica', '1', '2040002', '6', '0', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Álgebra Lineal y Numérica', '1', '2060006', '6', '0', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Ampliación de Cálculo', '1', '2260002', '6', '0', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Bioquímica Estructural', '1', '2260003', '6', '0', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Cálculo', '1', '2260006', '6', '0', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Cálculo Infinitesimal y Numérico', '1', '2050002', '6', '0', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Cálculo Infinitesimal y Numérico', '1', '2040007', '6', '0', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Cálculo Infinitesimal y Numérico', '1', '2060003', '6', '0', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Circuitos Electrónicos Digitales', '1', '2050003', '6', '0', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Circuitos Electrónicos Digitales', '1', '2040003', '6', '0', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Circuitos Electrónicos Digitales', '1', '2060004', '6', '0', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Estadística', '1', '2050008', '6', '0', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Estadística', '1', '2040008', '6', '0', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Estadística', '1', '2060007', '6', '0', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Estadística', '1', '2260007', '6', '0', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Estructura de Computadores', '1', '2050009', '6', '0', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Estructura de Computadores', '1', '2040009', '6', '0', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Estructura de Computadores', '1', '2060008', '6', '0', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Física I', '1', '2260004', '6', '0', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Física II', '1', '2260008', '6', '0', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Fundamentos de Programación', '1', '2050001', '12', '0', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Fundamentos de Programación', '1', '2040001', '12', '0', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Fundamentos de Programación', '1', '2060001', '12', '0', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Fundamentos de Programación', '1', '2260005', '6', '0', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Fundamentos Físicos de la Informática', '1', '2050004', '6', '0', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Fundamentos Físicos de la Informática', '1', '2040004', '6', '0', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Fundamentos Físicos de la Informática', '1', '2060009', '6', '0', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Gestión de Empresas', '1', '2260009', '6', '0', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Introducción a la Matemática Discreta', '1', '2050005', '6', '0', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Introducción a la Matemática Discreta', '1', '2040005', '6', '0', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Introducción a la Matemática Discreta', '1', '2060005', '6', '0', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Programación Orientada a Objetos', '1', '2260010', '6', '0', '4');

INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Ampliación de Matemáticas', '2', '2260011', '6', '1', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Análisis y Diseño de Datos y Algoritmos', '2', '2260011', '12', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Análisis y Diseño de Datos y Algoritmos', '2', '2040010', '12', '1', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Análisis y Diseño de Datos y Algoritmos', '2', '2060010', '12', '1', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Anatomía y Fisiología', '2', '2260016', '6', '1', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Arquitectura de Computadores', '2', '2050015', '6', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Arquitectura de Computadores', '2', '2040015', '6', '1', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Arquitectura de Computadores', '2', '2060015', '6', '1', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Arquitectura de Computadores y Sistemas Operativos', '2', '2260017', '6', '1', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Arquitectura e Integración de Sistemas Software', '2', '2050016', '6', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Arquitectura de Redes', '2', '2060016', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Bases de Datos', '2', '2260018', '6', '1', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Biología Celular y Genética', '2', '2260019', '6', '1', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Biología Molecular y Bioquímica', '2', '2260019', '6', '1', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Circuitos y Máquinas Eléctricas', '2', '2260013', '6', '1', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Control Automático', '2', '2260020', '6', '1', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Diseño de Sistemas Digitales', '2', '2040012', '6', '1', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Electrónica', '2', '2260014', '6', '1', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Estructuras de Datos y Algoritmos', '2', '2260015', '6', '1', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Introducción a la Ingeniería del Software y los Sistemas de Información I', '2', '2050046', '6', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Introducción a la Ingeniería del Software y los Sistemas de Información I', '2', '2040047', '6', '1', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Introducción a la Ingeniería del Software y los Sistemas de Información I', '2', '2060054', '6', '1', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Introducción a la Ingeniería del Software y los Sistemas de Información II', '2', '2050047', '6', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Introducción a la Ingeniería del Software y los Sistemas de Información II', '2', '2040048', '6', '1', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Introducción a la Ingeniería del Software y los Sistemas de Información II', '2', '2060055', '6', '1', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Lógica Informática', '2', '2050012', '6', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Lógica Informática', '2', '2060012', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Matemática Discreta', '2', '2050017', '6', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Matemática Discreta', '2', '2040016', '6', '1', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Matemática Discreta', '2', '2060013', '6', '1', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Redes de Computadores', '2', '2050013', '6', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Redes de Computadores', '2', '2040017', '6', '1', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Redes de Computadores', '2', '2060014', '6', '1', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Sistemas Operativos', '2', '2050014', '6', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Sistemas Operativos', '2', '2040013', '6', '1', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Sistemas Operativos', '2', '2060017', '6', '1', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Tecnología de Computadores', '2', '2040014', '6', '1', '2');

INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Ampliación de Inteligencia Artificial', '3', '2060025', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Análisis Avanzado de Datos Clínicos', '3', '2260026', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Arquitectura de Sistemas Distribuidos', '3', '2060026', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Arquitectura y Servicios de Redes', '3', '2050023', '6', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Arquitectura y Tecnología de Redes I', '3', '2040049', '6', '1', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Arquitectura y Tecnología de Redes II', '3', '2040050', '6', '1', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Biomateriales', '3', '2260028', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Biomecánica I: Sólidos', '3', '2260029', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Biomecánica II: Fluidos', '3', '2260030', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Biotecnología', '3', '2260031', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Ciencia y Resistencia de Materiales', '3', '2260032', '6', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Codificación y Gestión de la Información Sanitaria', '3', '2260033', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Configuración, Implementación y Mantenimiento de Sistemas Informáticos', '3', '2060018', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Desarrollo de Aplicaciones Distribuidas', '3', '2040023', '6', '1', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Diseño e Implementación de Sistemas de Información Clínica', '3', '2260034', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Diseño y Pruebas I', '3', '2050048', '6', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Diseño y Pruebas II', '3', '2050049', '6', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Fundamentos de Informática Clínica', '3', '2260021', '6', '1', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Geometría Computacional', '3', '2040024', '6', '1', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Gestión de Sistemas de Información', '3', '2060019', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Gestión y Estrategia Empresarial', '3', '2060020', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Ingeniería de Requisitos', '3', '2050020', '6', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Imágenes Biomédicas', '3', '2260022', '6', '1', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Infraestructuras de Sistemas de Información', '3', '2260036', '6', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Ingeniería del Software', '3', '2260023', '6', '1', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Instrumentación Biomédica', '3', '2260038', '6', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Inteligencia Artificial', '3', '2050024', '6', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Inteligencia Artificial', '3', '2040019', '6', '1', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Inteligencia Artificial', '3', '2060021', '6', '1', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Matemática Aplicada a Sistemas de Información', '3', '2060027', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Modelado y Simulación Numérica', '3', '2050021', '6', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Modelado y Visualización Gráfica', '3', '2050025', '6', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Periféricos e Interfaces', '3', '2040020', '6', '1', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Procesadores de Lenguajes', '3', '2060022', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Procesamiento de Señales Multimedia', '3', '2050022', '6', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Proceso Software y Gestión I', '3', '2050050', '6', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Proceso Software y Gestión II', '3', '2050051', '6', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Programación Declarativa', '3', '2060023', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Redes y Sistemas Distribuidos', '3', '2260024', '6', '1', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Salud Pública y Organización Sanitaria', '3', '2260041', '6', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Seguridad, Confidencialidad y Gestión de la Identidad', '3', '2260042', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Sistemas de Información Empresiales', '3', '2060028', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Sistemas Empotrados y de Tiempo Real I', '3', '2040025', '6', '1', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Sistemas Inteligentes', '3', '2060029', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Sistemas Inteligentes', '3', '2260025', '6', '1', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Sistemas Orientados a Servicios', '3', '2060030', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Sistemas Paralelos y Distribuidos', '3', '2040021', '6', '1', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Software de Sistemas', '3', '2040026', '6', '1', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Tecnologías Avanzadas de la Información', '3', '2060024', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Teoría de Grafos', '3', '2040022', '6', '1', '2');

INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Acceso Inteligente a la Información', '4', '2050027', '6', '2', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Acceso Inteligente a la Información', '4', '2040038', '6', '2', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Acceso Inteligente a la Información', '4', '2060032', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Administración de Sistemas de Información', '4', '2060033', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Ampliación de Administración de Empresas', '4', '2050028', '6', '2', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Aplicaciones de Soft Computing', '4', '2050029', '6', '2', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Aplicaciones de Soft Computing', '4', '2040039', '6', '2', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Aplicaciones de Soft Computing', '4', '2060044', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Arquitectura de Sistemas y Software de Base', '4', '2260047', '6', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Biofísica Celular y Tisular', '4', '2260063', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Bioseñales Médicas', '4', '2260064', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Complementos de Bases de Datos', '4', '2050037', '6', '2', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Computación Móvil', '4', '2060045', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Criptografía', '4', '2050030', '6', '2', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Criptografía', '4', '2040028', '6', '2', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Criptografía', '4', '2060046', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Derecho en la Informática', '4', '2050031', '6', '2', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Electromedicina', '4', '2260053', '6', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Estadística Computacional', '4', '2050038', '6', '2', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Estadística Computacional', '4', '2040029', '6', '2', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Estadística Computacional', '4', '2060047', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Etica y Legislación en Salud', '4', '2260065', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Evolución y Gestión de la Configuración', '4', '2050032', '6', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Gestión de la Producción', '4', '2050033', '6', '2', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Gestión de la Producción', '4', '2040031', '6', '2', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Gestión de la Producción', '4', '2060048', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Gestión de Procesos y Servicios', '4', '2060034', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Gestión de Proyectos Informáticos', '4', '2260055', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Gestión de Servicios y Tecnologías de la Información', '4', '2260056', '6', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Gestión del Cambio, Comunicación y Liderazgo', '4', '2260057', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Ingeniería del Software y Práctica Profesional', '4', '2050039', '6', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Infraestructura de Sistemas de Información', '4', '2060035', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Inteligencia Empresarial', '4', '2060049', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Interacción Persona-ordenador', '4', '2060037', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Ingeniería de Tejidos', '4', '2260066', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Instalaciones Hospitalarias', '4', '2260059', '6', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Laboratorio de Desarrollo de Hardware', '4', '2040032', '6', '1', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Métodos Cuantitativos de Gestión', '4', '2050034', '6', '2', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Matemática Aplicada a Tecnologías de la Información', '4', '2060038', '6', '2', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Matemáticas para la Computación', '4', '2060039', '6', '2', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Modelado y Análisis de Requisitos en Sistemas de Información', '4', '2060050', '6', '2', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Modelos de Computación y Complejidad', '4', '2060051', '6', '2', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Microtecnología y Nanotecnología en Biomedicina', '4', '2260068', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Minería de Datos Clínicos', '4', '2260060', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Optimización de Sistemas', '4', '2050041', '6', '2', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Planificación y Gestión de Proyectos Informáticos', '4', '2050035', '6', '1', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Planificación y Gestión de Proyectos Informáticos', '4', '2040033', '6', '1', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Planificación y Gestión de Proyectos Informáticos', '4', '2060040', '6', '1', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Plataformas Hardware de Aplicación Específica', '4', '2040041', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Prácticas Externas', '4', '2050026', '6', '2', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Prácticas Externas', '4', '2040027', '6', '2', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Prácticas Externas', '4', '2060031', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Prácticas Externas', '4', '2260070', '13.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Procesamiento de Imágenes Digitales', '4', '2050042', '6', '2', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Procesamiento de Imágenes Digitales', '4', '2040042', '6', '2', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Procesamiento de Imágenes Digitales', '4', '2060041', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Procesamiento Digital de Señales', '4', '2040034', '6', '2', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Proyectos en Informática Clínica', '4', '2260073', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Proyectos en Ingeniería Biomédica', '4', '2260074', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Robótica y Automatización', '4', '2040043', '6', '2', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Robótica Médica', '4', '2260075', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Seguridad en Sistemas Informáticos y en Internet', '4', '2050043', '6', '2', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Seguridad en Sistemas Informáticos y en Internet', '4', '2040035', '6', '2', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Sistemas de Adquisición y Control', '4', '2040044', '6', '2', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Sistemas Empotrados y de Tiempo Real II', '4', '2040036', '6', '1', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Seguridad en Sistemas Informáticos y en Internet', '4', '2060042', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Seguridad, Etica y Regulación en Ingeniería Biomédica', '4', '2260076', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Sistemas de Control y Biomecatrónica', '4', '2260077', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Sistemas de Información para Teleasistencia y Atención Remota', '4', '2260078', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Sistemas de Rehabilitación y Ayuda a la Discapacidad', '4', '2260079', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Tecnología, Informática y Sociedad', '4', '2050036', '6', '2', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Tecnología, Informática y Sociedad', '4', '2040037', '6', '2', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Tecnología, Informática y Sociedad', '4', '2060052', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Tecnologías para la Administración Electrónica', '4', '2260081', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Teledetección', '4', '2050044', '6', '2', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Teledetección', '4', '2040045', '6', '2', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Teledetección', '4', '2060043', '6', '2', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Telemedicina', '4', '2260082', '4.5', '2', '4');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Trabajo Fin de Grado', '4', '2050045', '12', '3', '1');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Trabajo Fin de Grado', '4', '2040046', '12', '3', '2');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Trabajo Fin de Grado', '4', '2060053', '12', '3', '3');
INSERT INTO `asignaturas` (`nombre`, `curso_id`, `codigo`, `creditos`, `tipo`, `grado_id`) VALUES ('Trabajo Fin de Grado', '4', '2260083', '12', '3', '4');









